// <auto-generated />
namespace ISSSTE.Tramites2015.Common.Security.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DelegationsCatalog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DelegationsCatalog));
        
        string IMigrationMetadata.Id
        {
            get { return "201412100038261_DelegationsCatalog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
