//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2015.Common.RenapoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.wserv.ecurp.dgti.segob.gob.mx", ConfigurationName="RenapoService.ConsultaPorCurpServicePortType")]
    public interface ConsultaPorCurpServicePortType {
        
        // CODEGEN: El parámetro 'sessionID' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:getConfirm")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getConfirm(ISSSTE.Tramites2015.Common.RenapoService.getConfirm request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:getConfirm")]
        System.Threading.Tasks.Task getConfirmAsync(ISSSTE.Tramites2015.Common.RenapoService.getConfirm request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:consultarPorCurp", ReplyAction="urn:consultarPorCurpResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpResponse consultarPorCurp(ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:consultarPorCurp", ReplyAction="urn:consultarPorCurpResponse")]
        System.Threading.Tasks.Task<ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpResponse> consultarPorCurpAsync(ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getConfirm", WrapperNamespace="http://services.wserv.ecurp.dgti.segob.gob.mx", IsWrapped=true)]
    public partial class getConfirm {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.wserv.ecurp.dgti.segob.gob.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.wserv.ecurp.dgti.segob.gob.mx", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mssg;
        
        public getConfirm() {
        }
        
        public getConfirm(string sessionID, string Mssg) {
            this.sessionID = sessionID;
            this.Mssg = Mssg;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.wserv.ecurp.dgti.segob.gob.mx/xsd")]
    public partial class DatosConsultaCurp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cveCurpField;
        
        private string cveEntidadEmisoraField;
        
        private string direccionIpField;
        
        private string passwordField;
        
        private int tipoTransaccionField;
        
        private bool tipoTransaccionFieldSpecified;
        
        private string usuarioField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string cveCurp {
            get {
                return this.cveCurpField;
            }
            set {
                this.cveCurpField = value;
                this.RaisePropertyChanged("cveCurp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string cveEntidadEmisora {
            get {
                return this.cveEntidadEmisoraField;
            }
            set {
                this.cveEntidadEmisoraField = value;
                this.RaisePropertyChanged("cveEntidadEmisora");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string direccionIp {
            get {
                return this.direccionIpField;
            }
            set {
                this.direccionIpField = value;
                this.RaisePropertyChanged("direccionIp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int tipoTransaccion {
            get {
                return this.tipoTransaccionField;
            }
            set {
                this.tipoTransaccionField = value;
                this.RaisePropertyChanged("tipoTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoTransaccionSpecified {
            get {
                return this.tipoTransaccionFieldSpecified;
            }
            set {
                this.tipoTransaccionFieldSpecified = value;
                this.RaisePropertyChanged("tipoTransaccionSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarPorCurp", WrapperNamespace="http://services.wserv.ecurp.dgti.segob.gob.mx", IsWrapped=true)]
    public partial class consultarPorCurpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.wserv.ecurp.dgti.segob.gob.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ISSSTE.Tramites2015.Common.RenapoService.DatosConsultaCurp datos;
        
        public consultarPorCurpRequest() {
        }
        
        public consultarPorCurpRequest(ISSSTE.Tramites2015.Common.RenapoService.DatosConsultaCurp datos) {
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarPorCurpResponse", WrapperNamespace="http://services.wserv.ecurp.dgti.segob.gob.mx", IsWrapped=true)]
    public partial class consultarPorCurpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.wserv.ecurp.dgti.segob.gob.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public consultarPorCurpResponse() {
        }
        
        public consultarPorCurpResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaPorCurpServicePortTypeChannel : ISSSTE.Tramites2015.Common.RenapoService.ConsultaPorCurpServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaPorCurpServicePortTypeClient : System.ServiceModel.ClientBase<ISSSTE.Tramites2015.Common.RenapoService.ConsultaPorCurpServicePortType>, ISSSTE.Tramites2015.Common.RenapoService.ConsultaPorCurpServicePortType {
        
        public ConsultaPorCurpServicePortTypeClient() {
        }
        
        public ConsultaPorCurpServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaPorCurpServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaPorCurpServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaPorCurpServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ISSSTE.Tramites2015.Common.RenapoService.ConsultaPorCurpServicePortType.getConfirm(ISSSTE.Tramites2015.Common.RenapoService.getConfirm request) {
            base.Channel.getConfirm(request);
        }
        
        public void getConfirm(string sessionID, string Mssg) {
            ISSSTE.Tramites2015.Common.RenapoService.getConfirm inValue = new ISSSTE.Tramites2015.Common.RenapoService.getConfirm();
            inValue.sessionID = sessionID;
            inValue.Mssg = Mssg;
            ((ISSSTE.Tramites2015.Common.RenapoService.ConsultaPorCurpServicePortType)(this)).getConfirm(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ISSSTE.Tramites2015.Common.RenapoService.ConsultaPorCurpServicePortType.getConfirmAsync(ISSSTE.Tramites2015.Common.RenapoService.getConfirm request) {
            return base.Channel.getConfirmAsync(request);
        }
        
        public System.Threading.Tasks.Task getConfirmAsync(string sessionID, string Mssg) {
            ISSSTE.Tramites2015.Common.RenapoService.getConfirm inValue = new ISSSTE.Tramites2015.Common.RenapoService.getConfirm();
            inValue.sessionID = sessionID;
            inValue.Mssg = Mssg;
            return ((ISSSTE.Tramites2015.Common.RenapoService.ConsultaPorCurpServicePortType)(this)).getConfirmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpResponse ISSSTE.Tramites2015.Common.RenapoService.ConsultaPorCurpServicePortType.consultarPorCurp(ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpRequest request) {
            return base.Channel.consultarPorCurp(request);
        }
        
        public string consultarPorCurp(ISSSTE.Tramites2015.Common.RenapoService.DatosConsultaCurp datos) {
            ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpRequest inValue = new ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpRequest();
            inValue.datos = datos;
            ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpResponse retVal = ((ISSSTE.Tramites2015.Common.RenapoService.ConsultaPorCurpServicePortType)(this)).consultarPorCurp(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpResponse> ISSSTE.Tramites2015.Common.RenapoService.ConsultaPorCurpServicePortType.consultarPorCurpAsync(ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpRequest request) {
            return base.Channel.consultarPorCurpAsync(request);
        }
        
        public System.Threading.Tasks.Task<ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpResponse> consultarPorCurpAsync(ISSSTE.Tramites2015.Common.RenapoService.DatosConsultaCurp datos) {
            ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpRequest inValue = new ISSSTE.Tramites2015.Common.RenapoService.consultarPorCurpRequest();
            inValue.datos = datos;
            return ((ISSSTE.Tramites2015.Common.RenapoService.ConsultaPorCurpServicePortType)(this)).consultarPorCurpAsync(inValue);
        }
    }
}
