//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2015.Common.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISSSTE.Tramites2015.Common.Util.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización Exitosa.
        /// </summary>
        public static string ActualizacionExitosa {
            get {
                return ResourceManager.GetString("ActualizacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización Fallida.
        /// </summary>
        public static string ActualizacionFallida {
            get {
                return ResourceManager.GetString("ActualizacionFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Exitosa.
        /// </summary>
        public static string ConsultaExitosa {
            get {
                return ResourceManager.GetString("ConsultaExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al realizar la consulta en {0}.
        /// </summary>
        public static string ConsultaFallida {
            get {
                return ResourceManager.GetString("ConsultaFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Sin Resultados.
        /// </summary>
        public static string ConsultaSinResultados {
            get {
                return ResourceManager.GetString("ConsultaSinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminación Exitosa.
        /// </summary>
        public static string EliminacionExitosa {
            get {
                return ResourceManager.GetString("EliminacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminación Fallida.
        /// </summary>
        public static string EliminacionFallida {
            get {
                return ResourceManager.GetString("EliminacionFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Exitoso.
        /// </summary>
        public static string RegistroExitoso {
            get {
                return ResourceManager.GetString("RegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al hacer el registro en {0}.
        /// </summary>
        public static string RegistroFallido {
            get {
                return ResourceManager.GetString("RegistroFallido", resourceCulture);
            }
        }
    }
}
